name: Build

on:
  push:
    branches: [alpha]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Node v18
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn
        
      - name: Run Lint
        run: yarn lint

      - name: Genarate Config
        run: node genConfig.js

      - name: Build project
        run: yarn build

      - name: Push to Alpha live✨
