name: Dist

on:
  push:
    branches: [ alpha ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn
        
      - name: Build project
        run: yarn build
        
      - name: Commit build files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "automated: generated `dist` for hosting"
          file_pattern: "."
          skip_dirty_check: false
          skip_fetch: false
        
