name: Preview

on:
  push:
    branches: [alpha-new]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Node v18
        uses: actions/setup-node@v2
        with:
          node-version: 18
          
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-

      - name: Install dependencies
        run: yarn

      - name: Run Lint
        run: yarn lint

      - name: Build project
        run: yarn build

      - name: Make a zip of build Folder
        run: zip -r build.zip build

      - name: Deploy to Netlify
        run: |
          curl -H "Content-Type: application/zip" \
          -H "Authorization: Bearer ${{ secrets.NETLIFY_TOKEN }}" \
          --data-binary "build.zip" \
          https://api.netlify.com/api/v1/sites
